package com.etfc.testrun;

public enum FailureCategory {
  COMMUNICATION_TIMEOUT,
  FIRMWARE_RESPONSE_MISMATCH,
  THRESHOLD_MISMATCH,
  DEVICE_UNAVAILABLE,
  ENVIRONMENT_FAILURE,
  TEST_HARNESS_FAILURE,
  FLAKY_TEST,
  UNCLASSIFIED
}
